name: Bug report
description: File a bug
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Steps to reproduce, expected vs actual
      placeholder: Describe clearly
    validations: {required: true}
  - type: textarea
    id: logs
    attributes:
      label: Logs/screenshots
      render: shell
  - type: input
    id: version
    attributes:
      label: Commit/tag

